# plot tour
# h/t https://uchicagoconsulting.wordpress.com/2011/04/18/how-to-draw-good-looking-maps-in-r/
plot_county_tour <- function(df, tour_order, title) {
  # We need the coordinates for the centroids in a data frame. While we could easily convert
  # `coords`, let's just use the original file from which it was derived. This has the same order 
  # as coords, which by default is just the locations sorted by FIPS value
  coordinates <- df
  
  # The result of `solve_TSP` is a list of integers listing the index of the locations in the 
  # order they are to be visited. Thus, if the solution starts in California, the first digit 
  # would be 4. That's why we added the "index" column early on. Armed with that, we can make
  # a list of the locations that is reordered according to the tour generated by the TSP algorithm.
  
  tour_coordinates = coordinates[as.numeric(tour_order), ]
  
  # the `segmented` boolean is going to determine whether we draw one long path or 48 short ones
  
  # let's check out our first 10 stops
  # print(tour_coordinates$name[1:10])
  
  # and number the locations in order of their place in the tour
  tour_coordinates$tour_order <- seq(1:NROW(tour_coordinates))
  
  # MAP
  # Start with state borders
  all_counties <- map_data("county") # Thanks for including this, ggplot2
  p <- ggplot()
  if (!missing(title)) {
    p <- p + labs(title = title) + theme(plot.title=element_text(hjust=0.5))
  }
  p <- p + geom_polygon( data=all_counties, aes(x=long, y=lat, group = group), colour="black", fill="white")
  
  # Plot the centroids. Order doesn't matter, so we can use tour_coordinates
  p <- p + geom_point( data=tour_coordinates, aes(x=long, y=lat), color="black", size=3)
  
  # Plot the path in one fell swoop. Let's color it according to its progress from start to end, red to green
  p <- p + geom_path(data = tour_coordinates, aes(x= long, y = lat, color=tour_order), size=2) +
    scale_colour_gradientn( colours = c( "darkblue", "purple", "red"),
                            breaks  = c( 0, NROW(tour_coordinates) / 2, NROW(tour_coordinates)),
                            limits  = c( 0, NROW(tour_coordinates)))
  p <- p + theme(legend.position="none")
  
  print(p)
  return(p)
}